# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Testing and Coverage Generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python_version: [3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]

    steps:  
    - name: Checkout Code   
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        # Make this better and not require requirements when you have time
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #python -m pip install pylint coverage
        pip install pylint coverage
        if ( Test-Path -Path .\requirements.txt ) { pip install -r requirements.txt }

    - name: Lint with pylint
      run: pylint --rcfile=.pylintrc --exit-zero cemake

    - name: Test with unittest
      run: coverage run -m unittest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true







